version: 2.1 
orbs:
  nais: 'navikt/nais-deployment@1.1.0'

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:10.16.0 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
      - run:
          name: build
          command: npm build


workflow:
  deploy-docker-and-nais:
    jobs:
      - nais/deploy:
          context: NAIS deployment     # gives you $DOCKER_USERNAME and $DOCKER_PASSWORD
          repo: navikt/WebARXaaS
          image: navikt/WebARXaaS
          github-app-id: 1337          # when authenticating as a Github application
          nais-template: nais.yaml
          environment: dev-fss
          team: team-anonymization          # needs to be identical in Kubernetes and Github
      
          

